// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppSample.Data;

namespace WebAppSample.Migrations
{
    [DbContext(typeof(MvcMountainContext))]
    partial class MvcMountainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppSample.Models.Mountain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClimbmingDate");

                    b.Property<string>("Comment");

                    b.Property<bool>("Complete");

                    b.Property<int>("Height");

                    b.Property<string>("MountainName");

                    b.Property<DateTime>("RegDate");

                    b.Property<DateTime>("UpdDate");

                    b.HasKey("Id");

                    b.ToTable("Mountain");
                });
#pragma warning restore 612, 618
        }
    }
}
